// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
/*QUAKED actor_Spetsnaz_e_civ_Kiparis (1.0 0.25 0.0) (-16 -16 0) (16 16 72) SPAWNER MAKEROOM UNDELETABLE ENEMYINFO SCRIPT_FORCESPAWN SM_PRIORITY
defaultmdl="c_rus_spetznaz_shotgun_fb"
"count" -- max AI to ever spawn from this spawner
SPAWNER -- makes this a spawner instead of a guy
MAKEROOM -- will try to delete an AI if spawning fails from too many AI
UNDELETABLE -- this AI (or AI spawned from here) cannot be deleted to make room for MAKEROOM guys
ENEMYINFO -- this AI when spawned will get a snapshot of perfect info about all enemies
SCRIPT_FORCESPAWN -- this AI will spawned even if players can see him spawning.
SM_PRIORITY -- Make the Spawn Manager spawn from this spawner before other spawners.
*/
main()
{
	self.animTree = "";
	self.team = "axis";
	self.type = "human";
	self.accuracy = 1;
	self.health = 150;
	self.weapon = "kiparis_sp";
	self.secondaryweapon = "";
	self.sidearm = "cz75_sp";
	self.grenadeWeapon = "frag_grenade_sp";
	self.grenadeAmmo = 2;
	self.csvInclude = "char_spetsnaz.csv";

	self setEngagementMinDist( 128.000000, 0.000000 );
	self setEngagementMaxDist( 512.000000, 1024.000000 );

	switch( codescripts\character::get_random_character(4) )
	{
	case 0:
		character\c_rus_spetnaz_undercover1::main();
		break;
	case 1:
		character\c_rus_spetnaz_undercover2::main();
		break;
	case 2:
		character\c_rus_spetnaz_undercover1a::main();
		break;
	case 3:
		character\c_rus_spetnaz_undercover2b::main();
		break;
	}
}

spawner()
{
	self setspawnerteam("axis");
}

precache()
{
	character\c_rus_spetnaz_undercover1::precache();
	character\c_rus_spetnaz_undercover2::precache();
	character\c_rus_spetnaz_undercover1a::precache();
	character\c_rus_spetnaz_undercover2b::precache();

	precacheItem("kiparis_sp");
	precacheItem("cz75_sp");
	precacheItem("frag_grenade_sp");
}
