// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_rus_engineer_headgear1";
	a[1] = "c_rus_engineer_headgear2";
	a[2] = "c_rus_engineer_headgear3";
	a[3] = "c_rus_engineer_headgear4";
	return a;
}
