// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_rus_military_head1_gas";
	a[1] = "c_rus_military_head2_gas";
	a[2] = "c_rus_military_head3_gas";
	a[3] = "c_rus_spetznaz_body1_head1_gas";
	a[4] = "c_rus_spetznaz_body2_head1_gas";
	return a;
}
