// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_rus_military_head1";
	a[1] = "c_rus_military_head2";
	a[2] = "c_rus_military_head3";
	a[3] = "c_rus_spetznaz_body1_head1";
	a[4] = "c_rus_spetznaz_body2_head1";
	return a;
}
