// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_ger_richtofen_dlc5_body");
	self.headModel = "c_ger_richtofen_dlc5_head";
	self attach(self.headModel, "", true);
	self.voice = "german";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_ger_richtofen_dlc5_body");
	precacheModel("c_ger_richtofen_dlc5_head");
}
