// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_zom_moon_tech_cap_1";
	a[1] = "c_zom_moon_tech_nocap";
	a[2] = "c_zom_moon_tech_nocap";
	a[3] = "c_zom_moon_tech_nocap";
	a[4] = "c_zom_moon_tech_nocap";
	a[5] = "c_zom_moon_tech_nocap";
	a[6] = "c_zom_moon_tech_nocap";
	return a;
}
