// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_usa_clark_fb_bruised_getwet");
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_usa_clark_fb_bruised_getwet");
}
