// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_rus_airplane_gassed_worker_fb");
	self.voice = "russian";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_rus_airplane_gassed_worker_fb");
}
