// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_cub_carlos_casual_fb");
	self.voice = "cuban";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_cub_carlos_casual_fb");
}
