// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_usa_cubrebel_bowman_fb");
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_usa_cubrebel_bowman_fb");
}
