// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_rus_spetsnaz_undercover_head_1";
	a[1] = "c_rus_spetsnaz_undercover_head_2";
	a[2] = "c_rus_spetsnaz_undercover_head_3";
	a[3] = "c_rus_spetsnaz_undercover_head_1_cap";
	a[4] = "c_rus_spetsnaz_undercover_head_2_cap";
	a[5] = "c_rus_spetsnaz_undercover_head_3_cap";
	a[6] = "c_rus_spetsnaz_undercover_head_bala3hole";
	a[7] = "c_rus_spetsnaz_undercover_head_bala1hole";
	a[8] = "c_rus_spetsnaz_undercover_head_bala3hole";
	a[9] = "c_rus_spetsnaz_undercover_head_bala1hole";
	return a;
}
