// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_vtn_civ_ub_jacket_1";
	a[1] = "c_vtn_civ_ub_jacket_2";
	a[2] = "c_vtn_civ_ub_jacket_3";
	a[3] = "c_vtn_civ_ub_jacket_4";
	a[4] = "c_vtn_civ_ub_long_sleeve_1";
	a[5] = "c_vtn_civ_ub_long_sleeve_2";
	a[6] = "c_vtn_civ_ub_long_sleeve_3";
	a[7] = "c_vtn_civ_ub_long_sleeve_4";
	a[8] = "c_vtn_civ_ub_tight_tshirt_3";
	a[9] = "c_vtn_civ_ub_tight_tshirt_4";
	a[10] = "c_vtn_civ_ub_polo_1";
	a[11] = "c_vtn_civ_ub_polo_2";
	a[12] = "c_vtn_civ_ub_polo_3";
	a[13] = "c_vtn_civ_ub_polo_4";
	a[14] = "c_vtn_civ_ub_short_sleeve_1";
	a[15] = "c_vtn_civ_ub_short_sleeve_2";
	a[16] = "c_vtn_civ_ub_short_sleeve_3";
	a[17] = "c_vtn_civ_ub_short_sleeve_4";
	a[18] = "c_vtn_civ_ub_tank_top_1";
	a[19] = "c_vtn_civ_ub_tank_top_2";
	a[20] = "c_vtn_civ_ub_tank_top_3";
	a[21] = "c_vtn_civ_ub_tank_top_4";
	a[22] = "c_vtn_civ_ub_tight_tshirt_1";
	a[23] = "c_vtn_civ_ub_tight_tshirt_2";
	return a;
}
