// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_zom_snow_camo_fb_zt");
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_zom_snow_camo_fb_zt");
}
