// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("char_ger_zombeng_body1_1");
	self.voice = "german";
	self.skeleton = "base";
}

precache()
{
	precacheModel("char_ger_zombeng_body1_1");
}
