// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_brt_fullahead_drone_fb");
	self.voice = "british";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_brt_fullahead_drone_fb");
}
