// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_ger_steiner_fullahead_fb");
	self.voice = "german";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_ger_steiner_fullahead_fb");
}
