// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_rus_fullahead_patrenko_fb");
	self.voice = "russian_english";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_rus_fullahead_patrenko_fb");
}
