// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_viet_zombie_sonic_body");
	self.headModel = "c_viet_zombie_sonic_head";
	self attach(self.headModel, "", true);
	self.hatModel = "c_viet_zombie_sonic_bandanna";
	self attach(self.hatModel);
	self.gearModel = "c_viet_zombie_sonic_shirt";
	self attach(self.gearModel, "", true);
	self.voice = "vietnamese";
	self.skeleton = "base";
	self.torsoDmg5 = "c_viet_zombie_sonic_g_headoff";
}

precache()
{
	precacheModel("c_viet_zombie_sonic_body");
	precacheModel("c_viet_zombie_sonic_head");
	precacheModel("c_viet_zombie_sonic_bandanna");
	precacheModel("c_viet_zombie_sonic_shirt");
	precacheModel("c_viet_zombie_sonic_g_headoff");
	precacheModel("c_viet_zombie_sonic_g_headoff");
}
