// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
/*QUAKED actor_zombie_monkey_stealer (1.0 0.25 0.0) (-16 -16 0) (16 16 72) SPAWNER MAKEROOM UNDELETABLE ENEMYINFO SCRIPT_FORCESPAWN SM_PRIORITY
defaultmdl="c_zombie_monkey"
"count" -- max AI to ever spawn from this spawner
SPAWNER -- makes this a spawner instead of a guy
MAKEROOM -- will try to delete an AI if spawning fails from too many AI
UNDELETABLE -- this AI (or AI spawned from here) cannot be deleted to make room for MAKEROOM guys
ENEMYINFO -- this AI when spawned will get a snapshot of perfect info about all enemies
SCRIPT_FORCESPAWN -- this AI will spawned even if players can see him spawning.
SM_PRIORITY -- Make the Spawn Manager spawn from this spawner before other spawners.
*/
main()
{
	self.animTree = "";
	self.team = "axis";
	self.type = "zombie";
	self.accuracy = 0.2;
	self.health = 100;
	self.weapon = "m1911_zm";
	self.secondaryweapon = "";
	self.sidearm = "m1911_zm";
	self.grenadeWeapon = "frag_grenade_zm";
	self.grenadeAmmo = 0;
	self.csvInclude = "";

	self setEngagementMinDist( 256.000000, 0.000000 );
	self setEngagementMaxDist( 768.000000, 1024.000000 );

	character\c_zom_monkey_stealer::main();
}

spawner()
{
	self setspawnerteam("axis");
}

precache()
{
	character\c_zom_monkey_stealer::precache();

	precacheItem("m1911_zm");
	precacheItem("m1911_zm");
	precacheItem("frag_grenade_zm");
}
