// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_zom_cosmo_head1";
	a[1] = "c_zom_cosmo_head2";
	a[2] = "c_zom_cosmo_head3";
	a[3] = "c_zom_cosmo_head4";
	a[4] = "c_zom_cosmo_head3_gasmask";
	return a;
}
