// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_zom_george_romero_light_fb");
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_zom_george_romero_light_fb");
}
