// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_zom_danny_trejo_fb_player");
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_zom_danny_trejo_fb_player");
}
