// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_rus_engineer1_body_orange");
	self.headModel = codescripts\character::randomElement(xmodelalias\c_rus_engineer_head_gas_alias::main());
	self attach(self.headModel, "", true);
	self.voice = "russian";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_rus_engineer1_body_orange");
	codescripts\character::precacheModelArray(xmodelalias\c_rus_engineer_head_gas_alias::main());
}
