// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_usa_rebirth_weaver_body");
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_usa_rebirth_weaver_body");
}
