// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_cub_civilians_hat1_1";
	a[1] = "c_cub_civilians_hat1_2";
	a[2] = "c_cub_civilians_hat1_3";
	a[3] = "c_cub_civilians_hat1_4";
	a[4] = "c_cub_civilians_hat2_1";
	a[5] = "c_cub_civilians_hat2_2";
	a[6] = "c_cub_civilians_hat2_3";
	a[7] = "c_cub_civilians_hat2_4";
	a[8] = "c_cub_civilians_nohat";
	a[9] = "c_cub_civilians_nohat";
	a[10] = "c_cub_civilians_nohat";
	a[11] = "c_cub_civilians_nohat";
	a[12] = "c_cub_civilians_nohat";
	a[13] = "c_cub_civilians_nohat";
	a[14] = "c_cub_civilians_nohat";
	a[15] = "c_cub_civilians_nohat";
	return a;
}
