// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_cub_civilians_upper1_1";
	a[1] = "c_cub_civilians_upper1_2";
	a[2] = "c_cub_civilians_upper1_3";
	a[3] = "c_cub_civilians_upper1_4";
	a[4] = "c_cub_civilians_upper2_1";
	a[5] = "c_cub_civilians_upper2_2";
	a[6] = "c_cub_civilians_upper2_3";
	a[7] = "c_cub_civilians_upper2_4";
	return a;
}
