// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_cub_civilians_head1";
	a[1] = "c_cub_civilians_head2";
	a[2] = "c_cub_civilians_head3";
	a[3] = "c_cub_civilians_head4";
	a[4] = "c_cub_civilians_head5";
	return a;
}
