// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_ger_richtofen_dlc2_body");
	self.voice = "german";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_ger_richtofen_dlc2_body");
}
