// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_vtn_civ_ub_tank_top_1";
	a[1] = "c_vtn_civ_ub_tank_top_2";
	a[2] = "c_vtn_civ_ub_tank_top_3";
	a[3] = "c_vtn_civ_ub_tank_top_4";
	a[4] = "c_vtn_civ_ub_tight_tshirt_1";
	a[5] = "c_vtn_civ_ub_tight_tshirt_2";
	a[6] = "c_vtn_civ_ub_tight_tshirt_3";
	a[7] = "c_vtn_civ_ub_tight_tshirt_4";
	a[8] = "c_vtn_civ_ub_no_shirt_1";
	a[9] = "c_vtn_civ_ub_no_shirt_1";
	a[10] = "c_vtn_civ_ub_no_shirt_1";
	a[11] = "c_vtn_civ_ub_no_shirt_1";
	return a;
}
