// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_vtn_civ_acc_flipflop_1";
	a[1] = "c_vtn_civ_acc_flipflop_2";
	a[2] = "c_vtn_civ_acc_flipflop_3";
	a[3] = "c_vtn_civ_acc_flipflop_4";
	a[4] = "c_vtn_civ_acc_thong_1";
	a[5] = "c_vtn_civ_acc_thong_2";
	a[6] = "c_vtn_civ_acc_thong_3";
	a[7] = "c_vtn_civ_acc_thong_4";
	a[8] = "c_vtn_civ_acc_no_shoes_1";
	a[9] = "c_vtn_civ_acc_no_shoes_2";
	a[10] = "c_vtn_civ_acc_no_shoes_3";
	a[11] = "c_vtn_civ_acc_no_shoes_4";
	a[12] = "c_vtn_civ_acc_sandal_1";
	a[13] = "c_vtn_civ_acc_sandal_2";
	a[14] = "c_vtn_civ_acc_sandal_3";
	a[15] = "c_vtn_civ_acc_sandal_4";
	return a;
}
