// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_vtn_civ_lb_sweat_pants_1";
	a[1] = "c_vtn_civ_lb_sweat_pants_2";
	a[2] = "c_vtn_civ_lb_sweat_pants_3";
	a[3] = "c_vtn_civ_lb_sweat_pants_4";
	a[4] = "c_vtn_civ_lb_pajama_1";
	a[5] = "c_vtn_civ_lb_pajama_2";
	a[6] = "c_vtn_civ_lb_pajama_3";
	a[7] = "c_vtn_civ_lb_pajama_4";
	a[8] = "c_vtn_civ_lb_shorts_1";
	a[9] = "c_vtn_civ_lb_shorts_2";
	a[10] = "c_vtn_civ_lb_shorts_3";
	a[11] = "c_vtn_civ_lb_shorts_4";
	return a;
}
